import React, { useRef, useState } from 'react'
import { motion } from 'motion/react'
import { Download, Share2, Printer, ExternalLink, QrCode, CheckCircle2, FileText } from 'lucide-react'
import type { PDFReportResult } from '@/services/pdf/pdfReportService'

interface PDFOutputProps {
  result: PDFReportResult
}

const OP_LABELS: Record<string, string> = {
  merge: 'Merge',
  annotate: 'Annotate',
  bookmark: 'Bookmark + TOC',
  optimize: 'Optimize',
  'html-fallback': 'HTML Report',
}

export default function PDFOutput({ result }: PDFOutputProps) {
  const { pdfBlobUrl, htmlReport, usedFoxitAPI, appliedOperations, fileSizeBytes, pageCount, reportData } =
    result
  const [copied, setCopied] = useState(false)
  const iframeRef = useRef<HTMLIFrameElement>(null)

  const shareUrl = reportData.meta.bundleShareUrl
  const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${encodeURIComponent(shareUrl)}`

  // ── Download PDF blob ──────────────────────────────────────────────────
  const handleDownload = () => {
    if (pdfBlobUrl) {
      const a = document.createElement('a')
      a.href = pdfBlobUrl
      a.download = `cartivo-bundle-${reportData.reportId}.pdf`
      a.click()
    }
  }

  // ── Print HTML report (fallback mode) ─────────────────────────────────
  const handlePrint = () => {
    if (htmlReport) {
      const win = window.open('', '_blank', 'width=900,height=700')
      if (win) {
        win.document.write(htmlReport)
        win.document.close()
        setTimeout(() => win.print(), 400)
      }
    } else if (pdfBlobUrl) {
      const win = window.open(pdfBlobUrl)
      win?.print()
    }
  }

  // ── Copy share link ────────────────────────────────────────────────────
  const handleCopyLink = async () => {
    await navigator.clipboard.writeText(shareUrl)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="space-y-6">
      {/* Success banner */}
      <motion.div
        initial={{ opacity: 0, scale: 0.96 }}
        animate={{ opacity: 1, scale: 1 }}
        className="flex items-center gap-3 bg-emerald-50 border border-emerald-200 rounded-xl p-4"
      >
        <CheckCircle2 className="w-6 h-6 text-emerald-500 flex-shrink-0" />
        <div>
          <p className="font-semibold text-emerald-800 text-sm">
            {usedFoxitAPI ? 'PDF generated and enhanced successfully!' : 'HTML report ready to print!'}
          </p>
          <p className="text-xs text-emerald-600 mt-0.5">
            Report ID: <strong>{reportData.reportId}</strong>
            {pageCount ? ` · ${pageCount} pages` : ''}
            {fileSizeBytes ? ` · ${(fileSizeBytes / 1024).toFixed(1)} KB` : ''}
          </p>
        </div>
      </motion.div>

      {/* Applied operations */}
      {appliedOperations.length > 0 && (
        <div>
          <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">
            {usedFoxitAPI ? 'Foxit PDF Services Applied' : 'Generation Method'}
          </p>
          <div className="flex flex-wrap gap-2">
            {appliedOperations.map((op) => (
              <span
                key={op}
                className="text-xs font-medium px-3 py-1 rounded-full border bg-indigo-50 text-indigo-600 border-indigo-200"
              >
                ✓ {OP_LABELS[op] ?? op}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* PDF preview (Foxit mode: iframe) */}
      {pdfBlobUrl && (
        <div className="rounded-xl overflow-hidden border border-slate-200 shadow-sm">
          <div className="bg-slate-800 px-4 py-2 flex items-center gap-2">
            <FileText className="w-4 h-4 text-slate-400" />
            <span className="text-xs text-slate-400 font-medium">PDF Preview</span>
            <span className="ml-auto text-xs text-slate-500">Generated by Foxit Document Generation API · Enhanced by Foxit PDF Services API</span>
          </div>
          <iframe
            ref={iframeRef}
            src={pdfBlobUrl}
            className="w-full"
            style={{ height: 500 }}
            title="PDF Report Preview"
          />
        </div>
      )}

      {/* HTML preview (fallback mode: iframe) */}
      {htmlReport && !pdfBlobUrl && (
        <div className="rounded-xl overflow-hidden border border-slate-200 shadow-sm">
          <div className="bg-slate-800 px-4 py-2 flex items-center gap-2">
            <FileText className="w-4 h-4 text-slate-400" />
            <span className="text-xs text-slate-400 font-medium">Report Preview</span>
            <span className="ml-auto text-xs text-slate-500">
              Demo mode — configure VITE_FOXIT_API_KEY to use Foxit APIs
            </span>
          </div>
          <iframe
            srcDoc={htmlReport}
            className="w-full bg-white"
            style={{ height: 500 }}
            title="Report Preview"
            sandbox="allow-same-origin"
          />
        </div>
      )}

      {/* Action buttons */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
        {/* Download */}
        {pdfBlobUrl && (
          <button
            onClick={handleDownload}
            className="flex items-center justify-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-semibold text-sm py-3 px-4 rounded-xl transition-colors"
          >
            <Download className="w-4 h-4" />
            Download PDF
          </button>
        )}

        {/* Print */}
        <button
          onClick={handlePrint}
          className="flex items-center justify-center gap-2 bg-slate-700 hover:bg-slate-800 text-white font-semibold text-sm py-3 px-4 rounded-xl transition-colors"
        >
          <Printer className="w-4 h-4" />
          {htmlReport && !pdfBlobUrl ? 'Print to PDF' : 'Print'}
        </button>

        {/* Copy link */}
        <button
          onClick={handleCopyLink}
          className={`flex items-center justify-center gap-2 font-semibold text-sm py-3 px-4 rounded-xl border transition-all ${
            copied
              ? 'bg-emerald-50 border-emerald-300 text-emerald-700'
              : 'bg-white hover:bg-slate-50 border-slate-200 text-slate-700'
          }`}
        >
          {copied ? (
            <>
              <CheckCircle2 className="w-4 h-4" />
              Copied!
            </>
          ) : (
            <>
              <Share2 className="w-4 h-4" />
              Copy Share Link
            </>
          )}
        </button>
      </div>

      {/* QR code + share */}
      <div className="flex flex-col sm:flex-row items-center gap-5 bg-slate-50 border border-slate-200 rounded-xl p-5">
        <div className="flex-shrink-0">
          <img
            src={qrUrl}
            alt="QR code for bundle"
            className="w-24 h-24 rounded-lg border border-slate-200 shadow-sm"
          />
        </div>
        <div className="flex-1 text-center sm:text-left space-y-1">
          <div className="flex items-center gap-2 justify-center sm:justify-start">
            <QrCode className="w-4 h-4 text-indigo-500" />
            <span className="text-sm font-semibold text-slate-700">Share This Bundle</span>
          </div>
          <p className="text-xs text-slate-500 break-all">{shareUrl}</p>
          <p className="text-xs text-slate-400">
            Scan with your phone to open this bundle on Cartivo
          </p>
        </div>
      </div>

      {/* Foxit API credit */}
      <div className="border border-dashed border-slate-200 rounded-xl p-4 space-y-2">
        <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide">Powered by</p>
        <div className="flex flex-wrap gap-3 text-xs">
          <a
            href="https://developers.foxit.com"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-1.5 text-indigo-600 hover:underline font-medium"
          >
            <ExternalLink className="w-3 h-3" />
            Foxit Document Generation API
          </a>
          <a
            href="https://developers.foxit.com"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-1.5 text-purple-600 hover:underline font-medium"
          >
            <ExternalLink className="w-3 h-3" />
            Foxit PDF Services API
          </a>
        </div>
      </div>
    </div>
  )
}
